### ISSUE TITLE
settimeout inside close function

### ISSUE THREAD

**Issue by mohammad-zr** [bigyanpoudel/react-global-modal#2]
Hi. Thanks for your useful library. Is it required to add [settimeout ](https://github.com/bigyanpoudel/react-global-modal/blob/main/src/ModalWrapper/WrapperGlobalComponent.tsx#L65) inside closing functions?
It's a bit laggy

**Comment by bigyanpoudel** [comment]
@mohammad-zr  if we remove the set timeout, we will experience some unusual behavior so for the time being I have reduced the time interval. Thank you.
