### ISSUE TITLE
Hi, this is not really an issue

### ISSUE THREAD

**Issue by FrameMuse** [bigyanpoudel/react-global-modal#4]
Hello, I'm just here to say it, no issues.

This library resembles very much that I created, which is [react-modal-global](https://www.npmjs.com/package/react-modal-global).
I'm not blaming or anything, I just wonder, if you don't mind, if yours inspired by mine.

**Comment by bigyanpoudel** [comment]
No, It's not. I wasn't aware it that you worked before.
